name: Environment

on:
  workflow_call:
    outputs:
      test-value:
        description: "test-value"
        value: ${{ jobs.url.outputs.test-value }}
permissions:
  id-token: write
  contents: write
  statuses: read


jobs:
  url:
    uses: ./.github/workflows/a.yml
    secrets: inherit

  s3-deploy:
    needs: [ url ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
